feat: OrderExample
hyperliquid-dex/ts-examples pull request #4
Opened 2024-12-23 07:27 UTC by 2hyunbin

@traderben 
Reflected your feedback. I made an example of placing an order using the existing sign method as it is.

2025-01-30 19:48 UTC, traderben requested changes
Thanks for putting this together! Just a few comments that hopefully shouldn't take too long

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +import { signStandardL1Action } from "./signings";
```suggestion
import { signStandardL1Action } from "./Signing";
```
also need to edit that file to export this

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +const wallet = privateKeyToAccount("0x-your-secret-key");
What do you think of adding a description at the top that mentions that you need to set your secret key and pulling this into a separate constant. Can also throw an error saying to set it instead of relying on the default bad key error.

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +const activePool = null;
nit: rename to vault_or_subaccount_address

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +const assetId = 0;
nit: can just inline with the other hard coded values

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +async function orderExample() {
move the order action declaration into here

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +    "https://api.hyperliquid.xyz/exchange",
add a comment that if changing this to testnet also need to edit Signing.tsx. Maybe also mention that this sends an actual order on mainnet in the comment

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +  coin: "BTC",
replace with asset since mapping coin names to assets is out of scope for this example

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +import { ethers } from "ethers";
remove unused import

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +    action: {
avoid repeating all the declarations. You should reuse the action so that they are guaranteed to match
```suggestion
    action: orderAction
```

2025-01-30 19:48 UTC, traderben commented on examples/OrderExample.tsx
> +const orderWire = orderRequestToOrderWire(orderRequest, assetId);
no need to pass assetId separately

2025-01-31 05:39 UTC, 2hyunbin commented
@traderben 
Thank you for your detailed feedback. I have modified the code according to the requirements.

2025-01-31 21:05 UTC, traderben reviewed
Thanks for updating. Just a couple more issues

2025-01-31 21:05 UTC, traderben commented on examples/OrderExample.tsx
> +  if (!PRIVATE_KEY || PRIVATE_KEY === "0x-your-secret-key") {
nit move this to above where you initialize  wallet otherwise the example will crash there

2025-01-31 21:05 UTC, traderben commented on examples/OrderExample.tsx
> +const orderRequest: OrderRequest = {
move this into orderExample. asset should be 0 and remove assetId field. Having two fields for the same thing can lead to inconsistency and confusion

2025-02-03 03:08 UTC, 2hyunbin commented
@traderben 
Edit completed

2025-02-03 17:47 UTC, traderben approved these changes

2025-02-03 17:48 UTC, merged